upstream cedar-frontend-designer-preview {
    server              127.0.0.1:4202;
}

server {
    listen              80;
    server_name         designer.metadatacenter.orgx;
    return              302 https://designer.metadatacenter.orgx$request_uri;
}

server {
    listen              443 ssl;
    server_name         designer.metadatacenter.orgx;
    ssl_certificate     /opt/homebrew/etc/nginx/cedar/ssl/designer.metadatacenter.orgx/designer.metadatacenter.orgx.crt;
    ssl_certificate_key /opt/homebrew/etc/nginx/cedar/ssl/designer.metadatacenter.orgx/designer.metadatacenter.orgx.key;
    location / {
        proxy_pass      http://cedar-frontend-designer-preview;
    }
    error_log           /Users/cedar-dev/CEDAR/log/frontend-template-designer/nginx-error.log warn;
    access_log          /Users/cedar-dev/CEDAR/log/frontend-template-designer/nginx-access.log combined if=$loggable;
}
