upstream cedar-frontend-workspace-preview {
    server              127.0.0.1:4201;
}

server {
    listen              80;
    server_name         workspace.metadatacenter.orgx;
    return              302 https://workspace.metadatacenter.orgx$request_uri;
}

server {
    listen              443 ssl;
    server_name         workspace.metadatacenter.orgx;
    ssl_certificate     /opt/homebrew/etc/nginx/cedar/ssl/workspace.metadatacenter.orgx/workspace.metadatacenter.orgx.crt;
    ssl_certificate_key /opt/homebrew/etc/nginx/cedar/ssl/workspace.metadatacenter.orgx/workspace.metadatacenter.orgx.key;
    location / {
        proxy_pass      http://cedar-frontend-workspace-preview;
    }
    error_log           /Users/cedar-dev/CEDAR/log/frontend-workspace/nginx-error.log warn;
    access_log          /Users/cedar-dev/CEDAR/log/frontend-workspace/nginx-access.log combined if=$loggable;
}
