server {
	listen		443 ssl;
	server_name	openview.staging.metadatacenter.org;
	include		conf.d/letsencrypt_ssl;

	root /srv/cedar/cedar-openview/cedar-openview-dist;

	location = /index.html { add_header Cache-Control "no-store" always; }
	location ^~ /config/ {
		add_header Cache-Control "no-store" always;
		try_files $uri =404;
	}
	location ~* \.[0-9a-f]{16}\.(js|css)$ {
		add_header Cache-Control "public, max-age=31536000, immutable" always;
		try_files $uri =404;
	}
	location / {
		add_header Cache-Control "no-cache" always;
		if ( $isInternalNetwork ) {
			rewrite ^ http://uptime.statuscake.com/?TestID=rrcYEek524;
		}
		try_files	$uri /index.html;
	}
	error_log	/srv/cedar/log/frontend-openview/nginx-error.log warn;
	access_log	/srv/cedar/log/frontend-openview/nginx-access.log combined if=$loggable;
}
