"""Find CEDAR templates that demand a static field in their instances.

A static field renders and holds nothing, so it is not a property of an
instance. Every CEDAR editor omits it when it builds one. A template that
nonetheless names a static field in `required`, in `@context.required`, or in
`@context.properties` therefore describes an instance no editor will ever
produce, and no instance of it can validate.

The Template Designer excludes a static field from `required` when the field is
created, and never revisits that decision: convert an existing field to a static
type and the entry it was given stays. The `@context` block has no such guard at
all, so any field carrying a property IRI is named there whatever its type.

Each affected template prints one line as it is found: its `description`, which
is where the editor that wrote it signs its name. `--verbose` adds the
identifier and the offending fields. The run tallies affected templates by
generator, read from those same descriptions.

    export CEDAR_API_KEY=...
    python3 cedar_static_required_audit.py --server https://resource.metadatacenter.org

GET only. The key is read from the environment, a one-line file, or a prompt,
and is never logged, written, or sent anywhere but the configured origin.
Counts are permission-scoped: complete means everything this key can enumerate.
"""
import argparse
import collections
import getpass
import json
import os
import re
import ssl
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterator, Optional

DEFAULT_SERVER = "https://resource.metadatacenter.org"
DEFAULT_PROGRESS_EVERY = 100
ARTIFACT_PATHS = {"template": "templates", "element": "template-elements"}
TYPE_ORDER = ("template", "element")

STATIC_TEMPLATE_FIELD = "StaticTemplateField"
TEMPLATE_ELEMENT = "TemplateElement"

# The three places a container can name a child. A static field belongs in none
# of them; `_ui.order` and `_ui.propertyLabels` are where it legitimately
# appears, and this says nothing about those.
LOCATIONS = ("required", "@context.required", "@context.properties")

# Both the Template Designer and the artifact library sign what they write, in
# the artifact's own `description`: "<name> schema generated by <generator>".
GENERATOR = re.compile(r"generated by (?:the )?(.+?)\s*$", re.IGNORECASE)
UNSIGNED = "(no generator named)"


class AuditError(Exception):
    pass


class AuthenticationError(AuditError):
    pass


class ResponseError(AuditError):
    pass


class _NoRedirect(urllib.request.HTTPRedirectHandler):
    """A redirect could send the key to another host, so refuse to follow one."""

    def redirect_request(self, req, fp, code, msg, headers, newurl):
        return None


def generator_of(description: Any) -> str:
    if not isinstance(description, str):
        return UNSIGNED
    match = GENERATOR.search(description)
    return match.group(1) if match else UNSIGNED


@dataclass
class Finding:
    artifact_type: str
    artifact_id: str
    artifact_name: str
    artifact_description: str
    container_path: str
    field_name: str
    field_description: str
    field_input_type: str
    field_looks_standalone: bool
    locations: list[str]
    property_iri: Optional[str]

    def record(self) -> dict[str, Any]:
        return {
            "artifactType": self.artifact_type,
            "artifactId": self.artifact_id,
            "artifactName": self.artifact_name,
            "artifactDescription": self.artifact_description,
            "artifactGenerator": generator_of(self.artifact_description),
            "containerPath": self.container_path,
            "staticField": self.field_name,
            "staticFieldInputType": self.field_input_type,
            "staticFieldLooksStandalone": self.field_looks_standalone,
            "staticFieldDescription": self.field_description,
            "staticFieldGenerator": generator_of(self.field_description),
            "locations": self.locations,
            "propertyIri": self.property_iri,
        }


@dataclass
class State:
    started: float = field(default_factory=time.monotonic)
    expected: dict[str, int] = field(default_factory=dict)
    attempted: int = 0            # enumerated and fetched, successfully or not
    inspected: int = 0            # fetched and actually examined
    fetch_errors: int = 0
    listing_errors: int = 0
    with_static: int = 0          # artifacts holding at least one static field
    affected: int = 0             # artifacts where at least one static field is named
    findings: int = 0
    batch_start: int = 0
    batch_affected: int = 0
    by_location: dict[str, int] = field(default_factory=lambda: {name: 0 for name in LOCATIONS})
    by_generator: collections.Counter = field(default_factory=collections.Counter)
    by_field_generator: collections.Counter = field(default_factory=collections.Counter)
    static_seen: collections.Counter = field(default_factory=collections.Counter)
    static_named: collections.Counter = field(default_factory=collections.Counter)
    origin_seen: collections.Counter = field(default_factory=collections.Counter)
    origin_named: collections.Counter = field(default_factory=collections.Counter)

    @property
    def planned_total(self) -> int:
        return sum(self.expected.values())

    @property
    def elapsed(self) -> float:
        return time.monotonic() - self.started


def local_type(at_type: Any) -> str:
    """The CEDAR core type name, without the IRI that carries it."""
    return str(at_type).rsplit("/", 1)[-1] if isinstance(at_type, str) else ""


def unwrap(child: Any) -> Optional[dict]:
    """A child schema, past the array wrapper a multi-cardinality child wears."""
    if not isinstance(child, dict):
        return None
    if child.get("type") == "array" and isinstance(child.get("items"), dict):
        return child["items"]
    return child


def container_children(container: Any) -> Iterator[tuple[str, dict, str]]:
    """Each declared child of a container, as (name, schema, CEDAR type name).

    Children are recognised by the `@type` they declare rather than by the shape
    of their name, so an envelope key is skipped because it declares no artifact
    type, not because a pattern happened to match it.
    """
    if not isinstance(container, dict):
        return
    properties = container.get("properties")
    if not isinstance(properties, dict):
        return
    for name, raw in properties.items():
        child = unwrap(raw)
        if child is None:
            continue
        kind = local_type(child.get("@type"))
        if kind:
            yield name, child, kind


def named_locations(container: dict, name: str) -> list[str]:
    """Which of the three lists name this child."""
    found = []
    required = container.get("required")
    if isinstance(required, list) and name in required:
        found.append("required")
    context = (container.get("properties") or {}).get("@context")
    if isinstance(context, dict):
        context_required = context.get("required")
        if isinstance(context_required, list) and name in context_required:
            found.append("@context.required")
        context_properties = context.get("properties")
        if isinstance(context_properties, dict) and name in context_properties:
            found.append("@context.properties")
    return found


def property_iri(container: dict, name: str) -> Optional[str]:
    entry = ((container.get("properties") or {}).get("@context") or {}).get("properties")
    if not isinstance(entry, dict) or not isinstance(entry.get(name), dict):
        return None
    values = entry[name].get("enum")
    return values[0] if isinstance(values, list) and values and isinstance(values[0], str) else None


def text(value: Any) -> str:
    return value if isinstance(value, str) else ""


def looks_standalone(child: dict) -> bool:
    """Whether this field was created as a first-class artifact of its own.

    A field created inline in a template carries no artifact-level provenance of
    its own. One created standalone and then added does: it was versioned and
    given a status before any template referred to it. The distinction matters
    because the two arrive by different code paths, and only the inline one is
    checked against `isStaticField` before being added to `required`.
    """
    return bool(child.get("pav:version") or child.get("bibo:status"))


def input_type_of(child: dict) -> str:
    """The `_ui.inputType` a static field renders as: richtext, image, page-break, and so on."""
    ui = child.get("_ui")
    value = ui.get("inputType") if isinstance(ui, dict) else None
    return value if isinstance(value, str) and value else "(no inputType)"


def inspect(artifact_type: str, artifact_id: str, artifact_name: str, artifact_description: str,
            container: Any, path: str = "/") -> tuple[list[Finding], collections.Counter]:
    """Findings for this container and everything nested in it, and the static types it holds.

    The counter is every static field seen, named or not. It is the denominator
    that turns a count of offending fields into a rate per input type.
    """
    findings: list[Finding] = []
    statics: collections.Counter = collections.Counter()
    for name, child, kind in container_children(container):
        if kind == STATIC_TEMPLATE_FIELD:
            input_type = input_type_of(child)
            standalone = looks_standalone(child)
            statics[(input_type, standalone)] += 1
            locations = named_locations(container, name)
            if locations:
                findings.append(Finding(
                    artifact_type, artifact_id, artifact_name, artifact_description, path, name,
                    text(child.get("description")), input_type, standalone, locations,
                    property_iri(container, name),
                ))
        elif kind == TEMPLATE_ELEMENT:
            nested, nested_statics = inspect(artifact_type, artifact_id, artifact_name,
                                             artifact_description, child, f"{path}{name}/")
            findings.extend(nested)
            statics.update(nested_statics)
    return findings, statics


class GetOnlyClient:
    """Small stdlib JSON client whose only public operation is GET."""

    def __init__(self, server: str, api_key: str, timeout: float, retries: int,
                 delay_ms: int, ca_file: Optional[str], allow_http: bool):
        self.server = server.rstrip("/")
        parsed = urllib.parse.urlsplit(self.server)
        if parsed.scheme not in ({"https", "http"} if allow_http else {"https"}):
            raise ValueError("--server must use HTTPS (use --allow-http only for a local test server)")
        if (not parsed.netloc or parsed.username or parsed.password or parsed.query
                or parsed.fragment or parsed.path not in {"", "/"}):
            raise ValueError("--server must be an origin URL such as https://resource.metadatacenter.org")
        self.origin = (parsed.scheme, parsed.netloc)
        self.api_key = api_key
        self.timeout = timeout
        self.retries = retries
        self.delay = max(0, delay_ms) / 1000
        context = ssl.create_default_context(cafile=ca_file) if parsed.scheme == "https" else None
        handlers: list[Any] = [_NoRedirect()]
        if context is not None:
            handlers.append(urllib.request.HTTPSHandler(context=context))
        self.opener = urllib.request.build_opener(*handlers)

    def get_json(self, path: str, query: Optional[dict[str, Any]] = None) -> Any:
        url = self.server + path
        if query:
            url += "?" + urllib.parse.urlencode(query)
        parsed = urllib.parse.urlsplit(url)
        if (parsed.scheme, parsed.netloc) != self.origin:
            raise ValueError("refusing to send the API key outside the configured origin")
        request = urllib.request.Request(
            url,
            headers={"Authorization": f"apiKey {self.api_key}", "Accept": "application/json"},
            method="GET",
        )
        for attempt in range(self.retries):
            if self.delay:
                time.sleep(self.delay)
            try:
                with self.opener.open(request, timeout=self.timeout) as response:
                    return json.load(response)
            except urllib.error.HTTPError as error:
                if error.code == 401:
                    raise AuthenticationError(
                        "401 Unauthorized; check CEDAR_API_KEY (sent with the CEDAR apiKey scheme)"
                    ) from None
                if error.code in {301, 302, 303, 307, 308}:
                    raise ResponseError(f"refusing redirect from {url}") from None
                if error.code in {429, 500, 502, 503, 504} and attempt < self.retries - 1:
                    retry_after = error.headers.get("Retry-After")
                    try:
                        wait = min(60.0, float(retry_after)) if retry_after else min(30.0, 2 ** attempt)
                    except (TypeError, ValueError):
                        wait = min(30.0, 2 ** attempt)
                    time.sleep(wait)
                    continue
                body = error.read(300).decode("utf-8", errors="replace")
                raise ResponseError(f"GET {url} returned {error.code}: {body}") from None
            except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as error:
                if attempt < self.retries - 1:
                    time.sleep(min(30.0, 2 ** attempt))
                    continue
                raise ResponseError(f"GET {url} failed: {type(error).__name__}: {error}") from None
        raise ResponseError(f"GET {url} exhausted its retry budget")


def search_page(client: GetOnlyClient, artifact_type: str, limit: int, offset: int) -> dict[str, Any]:
    data = client.get_json("/search-deep", {
        "resource_types": artifact_type,
        "version": "all",
        "publication_status": "all",
        "sort": "createdOnTS,name",
        "limit": limit,
        "offset": offset,
    })
    if (not isinstance(data, dict) or not isinstance(data.get("resources"), list)
            or not isinstance(data.get("totalCount"), int)):
        raise ResponseError(f"search-deep returned an unexpected body for {artifact_type}")
    return data


def iter_refs(client: GetOnlyClient, artifact_type: str, page_size: int, state: State,
              hard_limit: Optional[int]) -> Iterator[tuple[str, str]]:
    offset = 0
    seen: set[str] = set()
    while True:
        data = search_page(client, artifact_type, page_size, offset)
        resources = data.get("resources") or []
        total = data["totalCount"]
        if total != state.expected.get(artifact_type):
            state.expected[artifact_type] = total
        if not resources:
            break
        for resource in resources:
            if not isinstance(resource, dict) or not isinstance(resource.get("@id"), str):
                state.listing_errors += 1
                continue
            artifact_id = resource["@id"]
            if artifact_id in seen:
                continue
            seen.add(artifact_id)
            yield artifact_id, str(resource.get("schema:name") or "")
            if hard_limit is not None and len(seen) >= hard_limit:
                return
        offset += page_size
        if offset >= total:
            break


def percent(part: int, whole: int) -> float:
    return 100.0 * part / whole if whole > 0 else 0.0


def format_duration(seconds: float) -> str:
    rounded = max(0, int(round(seconds)))
    hours, remainder = divmod(rounded, 3600)
    minutes, secs = divmod(remainder, 60)
    if hours:
        return f"{hours}h{minutes:02d}m"
    if minutes:
        return f"{minutes}m{secs:02d}s"
    return f"{secs}s"


def elide(value: str, width: int) -> str:
    value = " ".join(value.split())
    return value if len(value) <= width else value[:width - 1] + "…"


def report_affected(state: State, name: str, artifact_id: str, description: str,
                    findings: list[Finding], width: int, verbose: bool) -> None:
    """Print one affected template as it is found, above the running tally.

    One line each by default, holding the description, since that is what names
    the editor that wrote the template. `--verbose` adds the identifier and the
    offending fields.
    """
    print(f"{state.affected:>6}  {elide(description or name or '(unnamed)', width)}")
    if verbose:
        print(f"        id {artifact_id}")
        for item in findings:
            where = item.container_path if item.container_path != "/" else "root"
            print(f"        ! {item.field_name}  in {where}  ->  {', '.join(item.locations)}")
            if item.field_description:
                print(f"          field description {elide(item.field_description, width)}")
    sys.stdout.flush()


def print_progress(state: State, final: bool = False) -> None:
    total = state.planned_total
    start = state.batch_start + 1 if state.attempted > state.batch_start else state.attempted
    timing = f"elapsed={format_duration(state.elapsed)}"
    if not final and 0 < state.attempted < total:
        eta = (total - state.attempted) * state.elapsed / state.attempted
        timing += f", eta={format_duration(eta)}"
    print(
        f"[{'final' if final else 'checkpoint'} {state.attempted}/{total} "
        f"{percent(state.attempted, total):.1f}%] batch {start}-{state.attempted}: "
        f"affected={state.batch_affected} batch/{state.affected} total "
        f"({percent(state.affected, state.inspected):.1f}% of inspected, "
        f"{percent(state.affected, state.with_static):.1f}% of those with a static field); "
        f"with-static={state.with_static}; findings={state.findings}; "
        f"fetch-errors={state.fetch_errors}; {timing}",
        flush=True,
    )


def open_private_text_file(path: Path, exclusive: bool = False):
    """Open a report as owner-only, refusing a symlink where the platform allows.

    `exclusive` refuses an existing file outright, in the same syscall that
    creates it. A run that truncated the previous run's findings on startup
    destroyed them before it had produced anything to replace them with.
    """
    flags = os.O_WRONLY | os.O_CREAT | (os.O_EXCL if exclusive else os.O_TRUNC)
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    descriptor = os.open(path, flags, 0o600)
    os.fchmod(descriptor, 0o600)
    return os.fdopen(descriptor, "w", encoding="utf-8")


def atomic_write_json(path: Path, value: dict[str, Any]) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    with open_private_text_file(temporary) as stream:
        json.dump(value, stream, indent=2, ensure_ascii=False)
        stream.write("\n")
    os.replace(temporary, path)


def summary_document(state: State, status: str, server: str, types: list[str]) -> dict[str, Any]:
    return {
        "status": status,
        "server": server,
        "scope": {
            "artifactTypes": types,
            "permissionScoped": True,
            "statement": "Complete means every artifact this API key can enumerate, not store-wide completeness.",
            "httpMethods": ["GET"],
        },
        "attempted": state.attempted,
        "inspected": state.inspected,
        "expectedByType": state.expected,
        "withStaticField": state.with_static,
        "affected": state.affected,
        "percentOfInspected": round(percent(state.affected, state.inspected), 3),
        "percentOfThoseWithStaticField": round(percent(state.affected, state.with_static), 3),
        "findings": state.findings,
        "findingsByLocation": state.by_location,
        "staticFieldsSeenByInputType": dict(state.static_seen.most_common()),
        "staticFieldsSeenByOrigin": dict(state.origin_seen.most_common()),
        "staticFieldsNamedByOrigin": dict(state.origin_named.most_common()),
        "staticFieldsNamedByInputType": dict(state.static_named.most_common()),
        "affectedByTemplateGenerator": dict(state.by_generator.most_common()),
        "findingsByFieldGenerator": dict(state.by_field_generator.most_common()),
        "fetchErrors": state.fetch_errors,
        "listingErrors": state.listing_errors,
        "elapsedSeconds": round(state.elapsed, 3),
    }


def run(arguments: argparse.Namespace, client: GetOnlyClient, stream, summary_path: Path) -> tuple[State, str]:
    state = State()
    status = "COMPLETE_FOR_KEY"

    def checkpoint(final: bool = False) -> None:
        print_progress(state, final=final)
        atomic_write_json(summary_path,
                          summary_document(state, status if final else "IN_PROGRESS",
                                           arguments.server, arguments.selected_types))
        state.batch_start = state.attempted
        state.batch_affected = 0

    try:
        for artifact_type in arguments.selected_types:
            state.expected[artifact_type] = search_page(client, artifact_type, 1, 0)["totalCount"]
        print(f"to inspect: {state.planned_total} "
              f"({', '.join(f'{k}={v}' for k, v in state.expected.items())})\n")

        for artifact_type in arguments.selected_types:
            for artifact_id, name in iter_refs(client, artifact_type, arguments.page_size,
                                               state, arguments.limit):
                path = f"/{ARTIFACT_PATHS[artifact_type]}/{urllib.parse.quote(artifact_id, safe='')}"
                state.attempted += 1
                try:
                    artifact = client.get_json(path)
                except AuthenticationError:
                    raise
                except AuditError as error:
                    state.fetch_errors += 1
                    print(f"! could not fetch {artifact_id}: {error}", file=sys.stderr)
                    continue

                description = text(artifact.get("description")) if isinstance(artifact, dict) else ""
                findings, statics = inspect(artifact_type, artifact_id, name, description, artifact)
                state.inspected += 1
                if statics:
                    state.with_static += 1
                    for (input_type, standalone), count in statics.items():
                        state.static_seen[input_type] += count
                        state.origin_seen["standalone" if standalone else "inline"] += count
                if findings:
                    state.affected += 1
                    state.batch_affected += 1
                    state.findings += len(findings)
                    state.by_generator[generator_of(description)] += 1
                    for item in findings:
                        for location in item.locations:
                            state.by_location[location] += 1
                        state.by_field_generator[generator_of(item.field_description)] += 1
                        state.static_named[item.field_input_type] += 1
                        state.origin_named["standalone" if item.field_looks_standalone
                                           else "inline"] += 1
                        stream.write(json.dumps(item.record(), ensure_ascii=False) + "\n")
                    stream.flush()
                    if not arguments.quiet:
                        report_affected(state, name, artifact_id, description, findings,
                                        arguments.description_width, arguments.verbose)
                if state.attempted % arguments.progress_every == 0:
                    checkpoint()

        if state.fetch_errors or state.listing_errors:
            status = "PARTIAL_ERRORS"
        elif arguments.limit is not None and state.attempted >= arguments.limit:
            status = f"SAMPLE_LIMIT_{arguments.limit}"
    except KeyboardInterrupt:
        status = "PARTIAL_INTERRUPTED"
    except AuthenticationError as error:
        status = "PARTIAL_AUTHENTICATION_ERROR"
        print(f"! {error}", file=sys.stderr)
    except Exception as error:  # noqa: BLE001 - the summary must record why a run stopped
        status = f"PARTIAL_{type(error).__name__.upper()}"
        print(f"! audit stopped: {type(error).__name__}: {error}", file=sys.stderr)
    finally:
        print()
        print_progress(state, final=True)
        atomic_write_json(summary_path,
                          summary_document(state, status, arguments.server, arguments.selected_types))
    return state, status


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Find templates that name a static field in required or @context.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="GET only. The JSONL holds findings, never a whole artifact and never the API key.",
    )
    parser.add_argument("--server", default=DEFAULT_SERVER,
                        help=f"resource server origin (default: {DEFAULT_SERVER})")
    parser.add_argument("--api-key-file",
                        help="read the API key from this one-line file; otherwise CEDAR_API_KEY or a prompt")
    parser.add_argument("--types", default="template",
                        help="comma-separated: template, element, or all (default: template)")
    parser.add_argument("--page-size", type=int, default=100, help="search-deep page size (default: 100)")
    parser.add_argument("--progress-every", type=int, default=DEFAULT_PROGRESS_EVERY,
                        help=f"checkpoint every N artifacts (default: {DEFAULT_PROGRESS_EVERY})")
    parser.add_argument("--limit", type=int, help="quick sample: stop after this many artifacts")
    parser.add_argument("--quiet", action="store_true",
                        help="tally only; do not print a line per affected template")
    parser.add_argument("--verbose", action="store_true",
                        help="also print each affected template's id and offending fields")
    parser.add_argument("--description-width", type=int, default=110,
                        help="truncate printed descriptions to this width (default: 110)")
    parser.add_argument("--out", default="cedar-static-required-findings.jsonl",
                        help="stream findings as JSONL (default: cedar-static-required-findings.jsonl)")
    parser.add_argument("--summary", help="summary JSON path (default: <out>-summary.json)")
    parser.add_argument("--timeout", type=float, default=90, help="per-request timeout (default: 90)")
    parser.add_argument("--retries", type=int, default=5, help="attempts for transient failures (default: 5)")
    parser.add_argument("--delay-ms", type=int, default=0, help="polite delay before every request")
    parser.add_argument("--ca-file", help="additional CA bundle for a private HTTPS deployment")
    parser.add_argument("--allow-http", action="store_true", help="allow plain HTTP; local test servers only")
    parser.add_argument("--force", action="store_true",
                        help="overwrite existing findings and summary files instead of refusing")
    parser.add_argument("--fail-on-findings", action="store_true",
                        help="exit 1 after a complete run when findings exist")
    return parser


def resolve_api_key(arguments: argparse.Namespace, parser: argparse.ArgumentParser) -> str:
    if arguments.api_key_file:
        try:
            key = Path(arguments.api_key_file).expanduser().read_text(encoding="utf-8").strip()
        except OSError as error:
            parser.error(f"cannot read --api-key-file: {error}")
    else:
        key = os.environ.get("CEDAR_API_KEY", "").strip()
    if not key and sys.stdin.isatty():
        key = getpass.getpass("CEDAR API key: ").strip()
    if not key:
        parser.error("set CEDAR_API_KEY, use --api-key-file, or run interactively to be prompted")
    if "\n" in key or "\r" in key:
        parser.error("API key must be one line")
    return key


def parse_types(value: str, parser: argparse.ArgumentParser) -> list[str]:
    types = [item.strip() for item in value.split(",") if item.strip()]
    if types == ["all"]:
        return list(TYPE_ORDER)
    unknown = set(types) - set(ARTIFACT_PATHS)
    if unknown or not types:
        parser.error(f"--types must name {list(TYPE_ORDER)} or all")
    return [kind for kind in TYPE_ORDER if kind in types]


def print_static_types(state: State) -> None:
    """Static fields seen against static fields named, per input type.

    The rate is what distinguishes a type that always ends up named from one
    that never does; a bare count of findings only reflects which type is common.
    """
    if not state.static_seen:
        return
    print("static fields by input type (named / seen):")
    for input_type, seen in state.static_seen.most_common():
        named = state.static_named.get(input_type, 0)
        print(f"    {named:>6} / {seen:<6} {percent(named, seen):>5.1f}%  {input_type}")
    print("static fields by how the field was created (named / seen):")
    for origin in ("standalone", "inline"):
        seen = state.origin_seen.get(origin, 0)
        named = state.origin_named.get(origin, 0)
        print(f"    {named:>6} / {seen:<6} {percent(named, seen):>5.1f}%  {origin}")


def print_counter(label: str, counter: collections.Counter, limit: int = 10) -> None:
    if not counter:
        return
    print(f"{label}:")
    for name, count in counter.most_common(limit):
        print(f"    {count:>6}  {name}")
    remaining = len(counter) - limit
    if remaining > 0:
        print(f"    {'':>6}  … and {remaining} more, in the summary JSON")


def main(argv: Optional[list[str]] = None) -> int:
    parser = build_parser()
    arguments = parser.parse_args(argv)
    for name in ("page_size", "progress_every", "retries", "description_width"):
        if getattr(arguments, name) <= 0:
            parser.error(f"--{name.replace('_', '-')} must be positive")
    if arguments.limit is not None and arguments.limit <= 0:
        parser.error("--limit must be positive")
    if arguments.timeout <= 0:
        parser.error("--timeout must be positive")
    arguments.selected_types = parse_types(arguments.types, parser)
    api_key = resolve_api_key(arguments, parser)

    findings_path = Path(arguments.out).expanduser()
    summary_path = Path(arguments.summary).expanduser() if arguments.summary else \
        findings_path.with_name(findings_path.stem + "-summary.json")
    if findings_path == summary_path:
        parser.error("--out and --summary must name different files")
    arguments.server = arguments.server.rstrip("/")
    findings_path.parent.mkdir(parents=True, exist_ok=True)
    if summary_path.exists() and not arguments.force:
        parser.error(f"{summary_path} already holds a previous run's summary; "
                     f"pass --summary to write elsewhere, or --force to overwrite it")

    try:
        client = GetOnlyClient(arguments.server, api_key, arguments.timeout, arguments.retries,
                               arguments.delay_ms, arguments.ca_file, arguments.allow_http)
    except (ValueError, OSError) as error:
        parser.error(str(error))

    print(f"GET-only scan of {arguments.server}")
    print(f"Scope: {', '.join(arguments.selected_types)}; permission-scoped to this key")
    print(f"Findings: {findings_path}; summary: {summary_path}")
    print(f"Checkpoint: every {arguments.progress_every} artifacts")

    try:
        with open_private_text_file(findings_path, exclusive=not arguments.force) as stream:
            state, status = run(arguments, client, stream, summary_path)
    except FileExistsError:
        parser.error(f"{findings_path} already holds a previous run's findings; "
                     f"pass --out to write elsewhere, or --force to overwrite it")
    except OSError as error:
        parser.error(f"cannot open findings file securely: {error}")

    print("\n=== Final summary ===")
    print(f"status: {status}")
    print(f"attempted: {state.attempted}/{state.planned_total} "
          f"({percent(state.attempted, state.planned_total):.1f}%); "
          f"inspected: {state.inspected}")
    print(f"holding at least one static field: {state.with_static} "
          f"({percent(state.with_static, state.inspected):.1f}% of inspected)")
    print(f"affected: {state.affected} "
          f"({percent(state.affected, state.inspected):.1f}% of inspected, "
          f"{percent(state.affected, state.with_static):.1f}% of those with a static field)")
    print(f"findings: {state.findings} "
          f"({', '.join(f'{k}={v}' for k, v in state.by_location.items())})")
    print_static_types(state)
    print_counter("affected templates by generator", state.by_generator)
    print_counter("findings by static-field generator", state.by_field_generator)
    print(f"fetch/listing errors: {state.fetch_errors}/{state.listing_errors}")
    print(f"details: {findings_path}")
    print(f"summary: {summary_path}")
    print("No artifact writes were issued; the HTTP client supports GET only.")

    if status.startswith("PARTIAL"):
        return 2
    if arguments.fail_on_findings and state.findings:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
